spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zerostep
    username: zerostep
    password: zerostep0370
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 10000
      idle-timeout: 300000
      max-lifetime: 600000
      pool-name: ZeroStepHikariPool

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

logging:
  level:
    root: INFO
    com.ahmedv2.zerostep: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE